### PR TITLE
Let's go golfing!

### PR DESCRIPTION
**Pull request by TwelveBaud**
These changes reduce the footprint of the game, which makes more room for more features.

* Developer-specific and output files have been removed; this makes it less likely for personal information to get included and any developer can recreate the output in their own copy of Atmel Studio.
* Since Atmel uses GCC, we can use GCC's extended assembly system. All the places where there are `NOP` instructions have been annotated so that the compiler knows they're not destructive to registers, and `drawSprite(theData)` can work even if the compiler doesn't use `R24` to pass the parameter.
* The `ADCSRB` register, which the compiler considers volatile, is additionally-used as the field counter for interlacing. More efficient assignment saves instructions.
* The `VLMCSR` register was additionally-used for pre-calculating which section of the screen is drawn. Every access needs to be indirected through a GPR. Since there are 11 usable GPRs, one's been assigned specifically for that purpose instead, removing the `IN` and `OUT` instructions.

These changes save 12 instruction bytes and cost no additional data bytes.

Additional improvements are possible, but beyond my current abilities:

* There's a division by 5 and a division by 10. This causes the software division function, which is about 14 bytes, to get linked in, plus 2 additional bytes at each call site. If those divisions can be done more efficiently -- multiply by a constant, divide by a power of two, for example -- that may save bytes and will save cycles.
* When the code is linked together, additional items are added by the linker: a reset vector (2 bytes), 7 other interrupt vectors (14 bytes), a memory-clear routine (48 bytes), a jump-to-reset trampoline (2 bytes), and some other miscellaneous code (8 bytes). Strictly speaking, only the reset vector and memory-clear routine are required, which would save 24 bytes. However, that requires writing a custom `crt0.S` file to get rid of the extraneous code, and the Atmel-supplied version is only available in compiled form.

### CODE REVIEW

**Comment by raybellis** [comment]
See also #2 which with your code gets the running total down to 988 bytes.    I am however getting a warning from your patch  to use `r26`:

```
main.c:6:18: warning: call-clobbered register used for global register variable
 register uint8_t lineMode asm ("r26");
```

**Comment by raybellis** [comment]
p.s. having Ben's actual output files was useful because the .lss file allowed me to confirm that my (Linux) build environment was producing the same output as his.

**Comment by TwelveBaud** [comment]
> I am however getting a warning from your patch to use `r26`:

The calling convention for AVR says that when you call another function it can use `r26` however it sees fit, and when you call a function in another compilation unit that doesn't know about this declaration it might overwrite that variable. However, all of the code is in this one compilation unit aside from the division function from `libm`, and that one doesn't use `r26` and isn't likely to change, so it should be fine.

**Comment by raybellis** [comment]
I've looked into the division by 5 and 10 issues, but I believe that in the absence of a hardware multiply instruction or a barrel shifter on the ATtiny10 there's no chance of making the current code any shorter.   It could probably be made _faster_ using a multiplication, but the resulting code would be larger.

The only obvious optimisation would be to arrange the bugs in e.g. four rows of eight, so that all divisions can be done with simple right-shifts, eliminating the `libm` code.

**Pull request merged**
